### PR TITLE
ProgramDescriptionArea now converts the lab times to user's local time

### PR DESCRIPTION
**Pull request by AngeredZeus**
Added some bold styling
Slightly reworded the How It Works section

### CODE REVIEW

**Comment by AngeredZeus** [comment]
Fixes this issue https://github.com/dev-launchers/platform__website/issues/366

**Comment by pyxld-kris** [comment]
Hey @AngeredZeus! First off, thanks a ton for helping with this. It looks like it's almost ready to be accepted, I'm just seeing one (maybe minor) issue.

Right now, on Sunday June 13th, the page is rendering the lab from yesterday on June12th:
image

I'm not sure how to test date changing on my end right now, but I'm going to check back in tomorrow. 

**Do you have any idea when it will move over to the next lab, and how we might be able to keep it more up to date?**

**Comment by AngeredZeus** [comment]
> Hey @AngeredZeus! First off, thanks a ton for helping with this. It looks like it's almost ready to be accepted, I'm just seeing one (maybe minor) issue.
> 
> Right now, on Sunday June 13th, the page is rendering the lab from yesterday on June12th:
> image
> 
> I'm not sure how to test date changing on my end right now, but I'm going to check back in tomorrow.
> 
> **Do you have any idea when it will move over to the next lab, and how we might be able to keep it more up to date?**

I didn't get the user's local time to set the week, should be an easy fix.

**Comment by pyxld-kris** [comment]
> I didn't get the user's local time to set the week, should be an easy fix.

Awesome, thank you so much! Just checked and the date *did* switch over today (Monday, June 14th)

image

**Comment by pyxld-kris** [comment]
@AngeredZeus Are you still planning on looking into this?

**Comment by AngeredZeus** [comment]
> @AngeredZeus Are you still planning on looking into this?

That last commit should fix this issue, should be good to go now. I added a check to see if the event had already occurred, if it has, it moves the date to the next week.

**Pull request merged**
