### PR TITLE
projects  page

### PR DESCRIPTION
**Pull request by Enjoy2Live**
- add Nunito Sans font
- feat(Enjoy2Live): adding projects route
- feat(Enjoy2Live): adding individual projects route

### CODE REVIEW

**Review by patomation — APPROVED** [review]
yep, theme variables are better than hard coded. Approved.

**Review by patomation — APPROVED** [review]
Noice.

**Review by pyxld-kris — CHANGES_REQUESTED** [review]
This is looking great! Visually, there are two things I'd like to try to work in if we can:

1) Some way to *really* draw people to individual projects. Maybe the ability to add images to each project? Or colors, icons, or emojis that make them easy to mentally parse? Here are some of the big reasons people may end up on this page, which should influence the design decisions:
      - **[Developers]** People who might be on the fence about joining our programs or contributing may end up on this page.
      - **[Donors and Companies]** People who are deciding about donating to the organization, or decision makers in companies that may sponsor Dev Launchers
      - **[Members]** With the changes we're making to Dev Launchers, we'll want a page we can send people to so they can find a project with a team they can join
    
2) The space between the two columns is a bit large on my screen. I've attached a screenshot here: 
image

**Review by chungthuang — APPROVED** [review]

**Review by pyxld-kris — APPROVED** [review]

**Pull request merged**
