### PR TITLE
Merge Menu dropdown into in-progress 

### PR DESCRIPTION
**Pull request by han1ya**
For Enjoy to merge into in-progress instead of master.

### CODE REVIEW

**Review by Enjoy2Live — CHANGES_REQUESTED** [review]
@han1ya the pull request needs minor fix which is not showing the menu button on smaller screens and instead integrate it into the hamburger menu/sidebar. see the attachment!

https://user-images.githubusercontent.com/27841994/120959052-9629a980-c761-11eb-88fc-a2d5c4e686df.mp4

**Comment by Enjoy2Live** [comment]
Other than that, I think it looks so good. thank you <3

**Comment by pyxld-kris** [comment]
I ran into a few errors when reviewing this

1) Something weird with an import maybe?
image

2) It looks like the environment variable wasn't changed back in the staging object
image

**Review by Enjoy2Live — APPROVED** [review]

**Pull request merged**
